import type { Metadata } from "next";
import { Onest, Playfair_Display, Syne } from "next/font/google";
import "./globals.css";

// Fonts
const inter = Syne({
  variable: "--title-font",
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

const poppins = Onest({
  variable: "--body-font",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--ex-font",
  weight: ["400", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={[
          inter.variable,
          poppins.variable,
          playfair.variable,
          "antialiased",
        ].join(" ")}
      >
        {children}
      </body>
    </html>
  );
}
